# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ImGui_config = debug
  App_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ImGui App

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C src/vendor/imgui -f Makefile config=$(ImGui_config)
endif

App: ImGui
ifneq (,$(App_config))
	@echo "==== Building App ($(App_config)) ===="
	@${MAKE} --no-print-directory -C . -f App.make config=$(App_config)
endif

clean:
	@${MAKE} --no-print-directory -C src/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C . -f App.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   App"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"